### ISSUE TITLE
Schema in the wrong directory

### ISSUE THREAD

**Issue by marrabld** [X3n0m0rph59/eruption-profile-switcher#2]
I tried installing the switcher from [Gnome Extensions](https://extensions.gnome.org/extension/2621/eruption-profile-switcher/)  site and got the following error when I tried to use the settings. 

``“~/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/schemas/gschemas.compiled”``

I checke the directory and saw there was no directory called `schemas` the the gschemas.compiled was in the directory above.   I created the directory by hand and copied the file over.  Seems to work fine now. 

Ubuntu 20.04.2 LTS
64bit 
Gnome 3.36.8
X11

**Comment by X3n0m0rph59** [comment]
@marrabld Thank you very much for reporting this issue!

This is a bug with the ZIP archive generation. I have uploaded a fixed ZIP archive to the GNOME Extensions repository, pending review.

eruption-profile-switcher revision 12:
[extension.zip](https://github.com/X3n0m0rph59/eruption-profile-switcher/files/5988211/extension.zip)

**Comment by X3n0m0rph59** [comment]
Revision 12 of the extension has been approved.

[eruption-profile-switcher](https://extensions.gnome.org/extension/2621/eruption-profile-switcher/)
