### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by poldolot** [X3n0m0rph59/eruption-profile-switcher#3]
Hi! During installation there is an error:

`gnome-shell[9038]: Ignoring excess values in shadow definition
gnome-shell[9038]: message repeated 7 times: [ Ignoring excess values in shadow definition]
gnome-shell[67520]: Archive:  /tmp/PE0S10.shell-extension.zip
gnome-shell[67520]:   inflating: /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/extension.js
gnome-shell[67520]:   inflating: /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/LICENSE
gnome-shell[67520]:   inflating: /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/prefs.js
gnome-shell[67520]:   inflating: /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/prefs.ui
gnome-shell[67520]:   inflating: /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/README.md
gnome-shell[67520]:    creating: /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/schemas/
gnome-shell[67520]:   inflating: /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/schemas/gschemas.compiled
gnome-shell[67520]:   inflating: /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/schemas/org.gnome.shell.extensions.eruption-profile-switcher.gschema.xml
gnome-shell[67520]:   inflating: /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/stylesheet.css
gnome-shell[67520]:  extracting: /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/metadata.json
gnome-shell[9038]: JS ERROR: Extension eruption-profile-switcher@x3n0m0rph59.org: SyntaxError: expected expression, got '?' @ /home/xxx/.local/share/gnome-shell/extensions/eruption-profile-switcher@x3n0m0rph59.org/extension.js:592
`

Thank You for great work with eruption driver and please help with this error :-)

**Comment by X3n0m0rph59** [comment]
Hi @poldolot, thank you for bringing this bug to my attention. Looks like your version of the GNOME shell does not support the null coalescing operator. I will fix this issue and upload a new extension package.

Could you please tell me:
* What distro are you using?
* What version of the GNOME shell are you using currently?

**Comment by poldolot** [comment]
I'm using Ubuntu 20.04 and GNOME in version 3.36.8 and GNOME Shell in 3.36.4.

**Comment by X3n0m0rph59** [comment]
@poldolot I have pushed the new release `v14` to the `master` branch. Please let me know if that fixes the issue

**Comment by poldolot** [comment]
Yes, that fixes the issue, thank You very much :-)
