### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by DerWeisse** [X3n0m0rph59/eruption-profile-switcher#4]
Hello,

I have barely any clue how to download this repo because that i'm asking to give me a short installation manual for Ubuntu.

Thanks. 

greetings Maxim

**Comment by cdemeijer** [comment]
I just installed the gnome extension as mentioned in the readme.
I am so happy I can switch the leds _off_. :) :100:

Roccat Burst Pro user. Will look into trying to contribute tonight.

**Comment by delauflahm** [comment]
Hello @DerWeisse

First of all: [RTFM](https://github.com/X3n0m0rph59/eruption-profile-switcher/blob/master/INSTALL.md)
Second: Install [Eruption](https://github.com/X3n0m0rph59/eruption/blob/master/docs/INSTALL.md#on-debian-based-distros) if you haven't already (Ubuntu is an on Debian-based distro) as far as I know it's also possible to install [Eruption](https://github.com/X3n0m0rph59/eruption) with following commands:

```
sudo add-apt-repository ppa:x3n0m0rph59/eruption
sudo apt install eruption
```

Thrid: In my case #5 this worked for installing eruption-profile-switcher:

You are able to download the file [here](https://extensions.gnome.org/extension/2621/eruption-profile-switcher/). You have to choose `the newest` (`highest -> today 41`) in the first field. After you clicked the newest (41) another window will pop up where you select also the `newest` (`highest -> today 20`).
Afterward, run the following commands in cmd:
```
gnome-extensions install -f [the folder where your downloaded File is located]/eruption-profile-switcherx3n0m0rph59.org.v20.shell-extension.zip
gnome-extensions enable eruption-profile-switcher@x3n0m0rph59.org
```
Then you should see a different color scheme if your device is supported which you can check [here](https://github.com/X3n0m0rph59/eruption#supported-devices).

After all these steps, you should be able to change your profiles with help of the GUI as already mentioned [here](https://github.com/X3n0m0rph59/eruption-profile-switcher/blob/master/README.md).

![screenshot-01](https://user-images.githubusercontent.com/95418065/155303623-47f32c15-8c38-42ae-9992-02351cdad9bd.jpg)
![screenshot-02](https://user-images.githubusercontent.com/95418065/155303620-e29f4154-6154-4749-b745-7048207ab9fe.jpg)
 
or with the following command:
```
eruptionctl switch profile [Profile-Name]
```
eg:
```
eruptionctl switch profile matrix.profile
eruptionctl switch profile solid.profile
eruptionctl switch profile solid-wave.profile
````

I hope you can use Eruption after this long Explanation.
delauflahm
