### ISSUE TITLE
Eruption makes the sliders of volume on gnome 42 too long

### ISSUE THREAD

**Issue by Nopraz** [X3n0m0rph59/eruption-profile-switcher#6]
When I enable this extension, it looks like all the other sliders on Gnome changes size too.

When Eruption is disabled : 
![Before Eruption](https://user-images.githubusercontent.com/12595433/169525867-3e3e4dd9-8d1e-40bd-a2c3-6b44000074f2.png)

When Eruption is enabled : 
![With eruption](https://user-images.githubusercontent.com/12595433/169525913-1ec4365b-303e-4f70-b916-caf08a48b764.png)

**Comment by X3n0m0rph59** [comment]
Hi @Nopraz, thank you very much for bringing this to my attention!

This seems to be a bug in the `stylesheet.css`. I will push a fix for this issue soon.
